### ISSUE TITLE
Naming Consistency in the AddOn List

### ISSUE THREAD

**Issue by Frurox** [N6REJ/AdiBags_Bears_Enchanting#12]
This is not an issue, but more something that has to do with Naming Consistency and hope is a simple and fast fix.
These look good
<img width="317" alt="image" src="https://user-images.githubusercontent.com/47403751/202544307-b198883c-9b8e-4ae0-a464-b89c6ca7740b.png">
These are missing the -
<img width="263" alt="image" src="https://user-images.githubusercontent.com/47403751/202544428-53dcb5b0-8fb7-40bb-8e5e-c7220f68cf69.png">

**Comment by N6REJ** [comment]
ty for reporting, resolved with 2022.11.18

**Comment by Frurox** [comment]
Thanks! Keep up the great work in taking these up, if you can do more that are out of date and make them your own would be great!

**Comment by Frurox** [comment]
All of them look good now except :)
<img width="226" alt="image" src="https://user-images.githubusercontent.com/47403751/202757073-b1c0ee5d-bf6b-4317-b6a9-7e3f27bafa03.png">
